using System.Collections;
using System.Collections.Generic;
using UnityEngine;




class MoleculeFactoryTester: MonoBehaviour {

    public TextAsset jsonFile;

    void Start(){
        MoleculeFactory factory = MoleculeFactory.getInstrance(this.jsonFile);
        //GameObject mol = factory.createMolecule("O2");
        GameObject mol2 = factory.createMolecule("H2O");
        //mol.transform.position = new Vector3(0,1,0);
        //GameObject bon = GameOject.CreatePrimitive(PrimitiveType.)
    }

}